### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft-API#1]
im getting this crash when downloading this api and putting it in my source files and then using the dev versions of this mod as Referenced Libraries???

Crash log: http://pastebin.com/9A3uYYiT

If i change back to a later version of both it all works fine. so its the api.

**Comment by micdoodle8** [comment]
This should be fixed as of the latest dev version downloads.

**Comment by MJRLegends** [comment]
Ok
