### ISSUE TITLE
OxygenHooks crash on dedicated server

### ISSUE THREAD

**Issue by ljfa-ag** [micdoodle8/Galacticraft-API#4]
RotaryCraft is crashing on the dedicated server because it uses the OxygenHooks.noAtmosphericCombustion method: http://pastebin.com/QMUsn033.
See ReikaKalseki/Reika_Mods_Issues#484.

The problem is that Galacticraft's OxygenUtil class is dependent on GuiScreen, even though only one of its methods is actually using it, but Reflection will actually load the paramter types of all methods.
Marking [OxygenUtil.shouldDisplayTankGui](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/util/OxygenUtil.java#L46) with `@SideOnly(Side.CLIENT)` would solve this.

**Comment by ErrorCraftLP** [comment]
This can be closed, it was fixed some time ago.

**Comment by ljfa-ag** [comment]
Ah, I forgot about it ^^

**Comment by radfast** [comment]
Thank you for raising this.  I wasn't working on the mod 22 December - 31 December but we fixed this asap in early January.

If any players encounter the issue, please advise them to update to latest Galacticraft.
