### ISSUE TITLE
OxygenHooks calling a method that doesn't exist

### ISSUE THREAD

**Issue by Vexxel** [micdoodle8/Galacticraft-API#7]
In [OxygenHooks.checkTorchHasOxygen](https://github.com/micdoodle8/Galacticraft-API/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/world/OxygenHooks.java), it's trying to get the method [OxygenUtil.isAABBInBreathableAirBlock(world, block, x, y, z)](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/util/OxygenUtil.java), which does not exist. I came across this error when using Rotarycraft engines on the moon (which require a valid atmosphere or oxygen bubble/sealed system).

**Comment by radfast** [comment]
Thank you, and sorry it's taken so long to fix this, I have been away from the mod for many months.
Fixed by https://github.com/micdoodle8/Galacticraft/commit/4d10c689f97cdc877c6f97a8c875d9606b5645b4
This fix will be in GC 3.0.12.472 and later versions
